name: Tag validation
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - '.metadata'
      - 'README.md'
      - '.github/**'
  pull_request:
jobs:
  tagValidation:
    name: Tag validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the version from the pubspec
        id: pubspecVersion
        uses: @cumulusds@v0.0.0
        with:
          file: pubspec.yaml
          version: version
      - name: Validate that version doesn't exists
        uses: mukunku/tag-exists-action@v1.0.0
        id: checkTag
        with:
          tag: ${{ steps.pubspecVersion.outputs.version }}
      - if: steps.checkTag.output.exists == "true"
        run: |
          echo "${{ steps.pubspecVersion.outputs.version }} already exists, please update the pubspec version."
          exit 1

  validationWorkflow:
    name: Tests and checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1

      # Get flutter dependencies.
      - run: flutter pub get

      # Check the format of the code and check if the code has any errors/warnings
      - run: flutter format --set-exit-if-changed .
      - run: flutter analyze

      # Run the tests
      - run: flutter test

      # TODO add coverage and coverage badge in case of pushing on master

  buildWorkflow:
    name: Build the application for
    needs: validationWorkflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1

      # Get flutter dependencies.
      - run: flutter pub get

      - name: Build APK for Android
        run: flutter build apk
